######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 6 10:50:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += random.h
SOURCES += main.cpp random.cpp
