######################################################################
# Automatically generated by qmake (2.01a) Thu May 19 09:24:04 2011
######################################################################
QT       += network
TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += random.h \
    excelengine.h
FORMS +=
SOURCES += main.cpp random.cpp \
    excelengine.cpp
RC_FILE = my.rc
CONFIG  += qaxcontainer
